apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weather-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: enginf_exercise_web
    spec:
      containers:
        - name: enginf_exercise_web
          image: enginf_exercise_web:latest
          ports:
            - containerPort: 8000
          args: ["foreground"]
          env:
            - name: HOST
              value: "example.com"
            - name: SECRET_KEY_BASE
              value: "highlysecretkey"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_NAME
              value: "testdb"
            - name: DB_HOSTNAME
              value: "x.x.x.x"
